language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
os:
  - linux
  - osx
install:
  - pip install unittest2
  - pip install 'coverage<4'
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: ./coverage.sh
